[project]
name = "multi-mcp-servers"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mcp[cli]>=1.11.0",
    "pyautogui>=0.9.54",
    "requests>=2.32.4",
]
